import '../src/js/best-sellers.js';
import './js/aside-menu/categories-menu.js';
import './js/aside-menu/charity-bar.js';
import './js/header.js'
import '/src/js/authorization.js';
import './js/category-books-list/category-books-list.js'
import './js/theme.js'
import '../src/js/scroll-up.js';
import '../src/js/loader.js';
import '../src/js/category-books-list/modal/book-pop-up.js'